development:
  :address: smtpout.mx.facebook.com
  :port: 25
  :authentication: plain
  :user_name: shinguyen195@gmail.com
  :password: Thienthan1!
  :enable_starttls_auto: true
production:
  :address: smtpout.mx.facebook.com
  :port: 25
  :authentication: plain
  :user_name: shinguyen195@gmail.com
  :password: Thienthan1!
  :enable_starttls_auto: true
