development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: youth.noreply@gmail.com
  :password: Thienthan1!
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: youth.noreply@gmail.com
  :password: Thienthan1!
  :enable_starttls_auto: true
